package generator

import "github.com/kefniark/mango-sql/internal/core"

type PostgresCtx struct {
	Const string
}

type PostgresTable struct {
	schema *core.SQLSchema
	table  *core.SQLTable
	driver string

	Name               string
	NameNormalized     string
	HasCompositeId     bool
	HasIdAutoGenerated bool
	ColumnIds          []*PostgresColumn
	Columns            []*PostgresColumn
	ColumnsCreate      []*PostgresColumn
	ColumnsUpdate      []*PostgresColumn
	Primary            []string
}

type PostgresColumn struct {
	Name           string
	NameNormalized string
	NameJson       string
	Type           string
	TypeSql        string
	Nullable       bool
	IsArray        bool
	HasDefault     bool
}

type PostgresQuery struct {
	Name           string
	NameNormalized string
	Method         string
	Fields         []*PostgresColumn
	SqlQuery       string

	Select         string
	SelectOriginal string
	From           string
	Where          string
	GroupBy        []string
	Having         string
}

type SelectFieldFilter struct {
	Model     string
	Table     string
	Name      string
	Field     string
	FieldType string
	Type      string
}

type FilterMethod struct {
	Name    string
	Filters []SelectFilter
}

type SelectFilter struct {
	Model   string
	Name    string
	Pre     string
	Comment string
	PreSql  string
	Sql     string
	Args    []string
}

type SelectQueryRef struct {
	FromTable  string
	ToTable    string
	Fields     []*PostgresColumn
	GetMethod  string
	Ref        string
	FromAccess string
}

type SelectQuery struct {
	Name   string
	Fields []*PostgresColumn
	Method string
}

type HeaderData struct {
	Package     string
	Url         string
	Date        string
	Version     string
	Deps        []string
	Placeholder string
}
