name: Create a Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (semver: x.y.z)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ github.event.inputs.version }}
