name: Create a Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (eg. v0.2.1)'
        required: true

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          # Configure git
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          # Create a tag and push it
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
