name: Create a Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (eg. v0.2.1)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ github.event.inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
